### PR TITLE
fix: `onOpenChange` getting called twice when user clicks outside of the drawer

### PR DESCRIPTION
**Pull request by phxgg**
Fixes: https://github.com/emilkowalski/vaul/issues/290

I tried to test as many possibilities as I could, and I couldn't find anything that breaks by deleting that line of code.

### CODE REVIEW

**Comment by phxgg** [comment]
You said on this comment https://github.com/emilkowalski/vaul/issues/290#issuecomment-2002150057 that it was fixed in #297 

However, #298 reintroduces the issue. I guess this is by accident?

**Comment by Semkoo** [comment]
This issue still appears with me, I have a small quick hack for now waiting on this change 

``` 
...
const [isFirstTimeOpened, setIsFirstTimeOpened] = useState(true);
...
const handleOnOpenChanges = useCallback(
    (aVal: boolean) => {
      if (isFirstTimeOpened) {
        setIsFirstTimeOpened(false);
        return;
      }
     ....
     }, [...]
);
... 

return (
    <Drawer
      open={open}
      onOpenChange={handleOnOpenChanges}
      direction={isDesktop ? "right" : "bottom"}
    >
    ... 
     </Drawer>
  );
};

**Comment by artemis-prime** [comment]
Good call!  That callback doesn't belong there, since closeDrawer(), which is below it, calls it as well

**Comment by emilkowalski** [comment]
Fixed in #408

**Pull request closed without merging**
