### PR TITLE
feat: support parent container

### LINKED ISSUE #296: Add ability to set parent container
The drawer dimensions are currently determined based on the viewport size. However, it would be beneficial to allow the specification of a container element for these calculations. This would enable the drawer to be used within a specific containing element, rather than occupying the entire screen.

### PR DESCRIPTION
**Pull request by joaom00**
This PR adds support for a parent container via `container` prop on `Root`

Fixes #296

### CODE REVIEW

**Review by danim47c — APPROVED** [review]
Seem to be perfect, working properly

**Review by itsjoeoui — APPROVED** [review]

**Comment by RahulBirCodes** [comment]
Seems to be working great, any updates on getting this merged? Currently facing a bottleneck without this feature.

**Comment by mandrillxx** [comment]
this would be really nice to have added

**Comment by emilkowalski** [comment]
Fixed in #413, hugely inspired by this PR, thanks @joaom00.

**Pull request closed without merging**
