### PR TITLE
cleanup bg on body

### PR DESCRIPTION
**Pull request by choeqq**
### Issues:
- https://github.com/emilkowalski/vaul/issues/228
- https://github.com/emilkowalski/vaul/issues/188

### CODE REVIEW

**Comment by emilkowalski** [comment]
We need to use the `reset` function instead of `set`. What if the user had a different background color set initially? That's what the `reset` function accounts for.

**Comment by choeqq** [comment]
this solution seems little hacky, I set up bg to `''` initially, to save it in cache, so when using reset we can get those from that cache, please let me know WDYT about that 🤔 

@emilkowalski

**Comment by emilkowalski** [comment]
`this solution seems little hacky, I set up bg to '' initially, to save it in cache, so when using reset we can get those from that cache, please let me know WDYT about that 🤔`

We can do something like `document.body.style.backgroundColor || document.body.style.background` instead of `''`

**Comment by choeqq** [comment]
right, that's better, just pushed the commit

**Pull request merged**
