### PR TITLE
fix(src): Replace `React.useLayoutEffect` with `useIsomorphicLayoutEffect`

### LINKED ISSUE #351: Warning: useLayoutEffect does nothing on the server when using Drawer from vaul in Nextjs 13
Screenshot 2024-05-14 at 20 16 50

```bash
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Root (file://clients/web/node_modules/.pnpm/vaul@0.9.1_@types+react-dom@18.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0/node_modules/vaul/dist/index.mjs:749:23)
    at Drawer
```

i have use shadcn drawer and i believe its extending vaul in the components.
so i have this error in every page or component that using Drawer from Vaul

Is there any solutions to supress this warning?

### LINKED ISSUE #367: Warning: useLayoutEffect does nothing on the server [...]
### Issue

I use Vaul inside a Remix app with vite and react@18.2.0. During development, Vite raises the following warning:

*Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.*

### Potential solution

This error is common with `useLayoutEffect` and the work-around is usually to create a `useIsomorphicLayoutEffect` hook, which you did in "vaul/src/use-prevent-scroll.ts":

```ts
export const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;
```

However, `React.useLayoutEffect` is still referenced in "vaul/src/index.tsx" at line 456:

```ts

// LayoutEffect to prevent extra render where openProp and isOpen are not synced yet
456 | React.useLayoutEffect(() => {
457 | if (openProp) {
458 | setIsOpen(true);
459 | setHasBeenOpened(true);


```

I believe switching to `useIsomorphicLayoutEffect` would solve the issue ? Or maybe I am missing something and the warning should be ignored ?

```ts

// LayoutEffect to prevent extra render where openProp and isOpen are not synced yet
456 | useIsomorphicLayoutEffect(() => {
457 | if (openProp) {
458 | setIsOpen(true);
459 | setHasBeenOpened(true);


```

### PR DESCRIPTION
**Pull request by axeldesutter**
Closes #367
Closes #351

### CODE REVIEW

**Comment by vsnthdev** [comment]
+1 please merge @emilkowalski

**Comment by Angel-Dijoux** [comment]
+1 please merge @emilkowalski  It's a need for server side rendering things!

**Comment by alescrocaro** [comment]
+1 pls merge @emilkowalski

**Comment by anapalmeida** [comment]
+1 pls merge @emilkowalski

**Comment by davidesigner** [comment]
+1 pls merge @emilkowalski 🙏 thx

**Pull request merged**
