### PR TITLE
Use CSS Animations for entry and exit animations

### LINKED ISSUE #292: Forward the defaultOpen prop
I have a map in the drawer with markers on it. The user can navigate away from the opened drawer with the map when clicked on a location, but when they navigate back i open the drawer for them, but it comes with the drawer open animation which makes it very ugly. 

This defaultOpen prop is already there in the radix part, why not passing it down?

### PR DESCRIPTION
**Pull request by joaom00**
This PR adds the use of CSS animations for Vaul entry and exit animations, making the code for managing the open state simpler.

I also refactored the logic of the scaleBackground function by changing

- Taking advantage of the `Content` component to be mounted/unmounted when the dialog is open or closed
- Created two utility functions `assignStyle` and `chain` that together facilitate the editing of styles and their cleaning

Fixes #292

### CODE REVIEW

**Comment by rortan134** [comment]
Also closes #351

**Comment by proggarapsody** [comment]
also it resolves #361

**Comment by danchistyakov** [comment]
@emilkowalski ?

**Comment by GA1** [comment]
any update on this @emilkowalski ?

**Comment by emilkowalski** [comment]
A fix inspired by this PR has landed in #408.

**Pull request closed without merging**
