### PR TITLE
Don't hide sticky elements

### PR DESCRIPTION
**Pull request by emilkowalski**

### CODE REVIEW

**Comment by emilkowalski** [comment]
Very soon!

**Comment by emilkowalski** [comment]
@Dearest This is live now!

**Comment by jsefiani** [comment]
Hey @emilkowalski, I just tested out the latest version, and I noticed that scrolling up inside a drawer doesn't work anymore, most likely because of this change.

**Comment by emilkowalski** [comment]
Where doesn't it work? It works fine for me in the codesandbox demo.
https://github.com/emilkowalski/vaul/assets/36730035/8d6f33fa-a6e2-40c4-bf01-9ba7b68cb762

**Comment by Lcarv20** [comment]
Hi there, sorry for bringing this back up, but I am using the latest version and the sticky components still disappear. Maybe I am doing something wrong, would you care to take a look at this sandbox?

- [sandbox](https://codesandbox.io/p/devbox/bottom-drawer-sticky-lh2g77?file=%2Fapp%2Flayout.tsx%3A20%2C52&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrtvh58u00073b6ona13pmt9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrtvh58u00023b6odncsmeaw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrtvh58u00043b6ofpsk09az%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrtvh58u00063b6of9h4x8ka%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B78.74372347090956%252C21.256276529090442%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrtvh58u00023b6odncsmeaw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtvh58t00013b6ogg88ia19%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrtymwcy00023b6omug2hn0r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrtz2oec00023b6on34osv9f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A52%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrtvh58u00023b6odncsmeaw%2522%252C%2522activeTabId%2522%253A%2522clrtz2oec00023b6on34osv9f%2522%257D%252C%2522clrtvh58u00063b6of9h4x8ka%2522%253A%257B%2522id%2522%253A%2522clrtvh58u00063b6of9h4x8ka%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtvh58u00053b6oeutkj2vc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtvh58u00053b6oeutkj2vc%2522%257D%252C%2522clrtvh58u00043b6ofpsk09az%2522%253A%257B%2522id%2522%253A%2522clrtvh58u00043b6ofpsk09az%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtvh58u00033b6o90u7sejm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtvh58u00033b6o90u7sejm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A11.675531914893611%257D)

#191 #143

**Pull request merged**
